name: Create a comment on new issues

on: 
  issues:
    types: [opened]
jobs:
 comment-with-api:
   runs-on: windows-latest
   steps:
     - name: Create comment with API
       run: |
         gh api -X POST \
           http://api.github.com/repos/{ORGANIZATION}/{REPOSITORY}/issues/{ISSUE_NUMBER}/comments \ 
           -f body='
           Comment from the API call
           '
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
         ORGANIZATION: ${{ github.event.organisation.login }} 
         REPOSITORY: ${{ github.event.repository.name }}
         ISSUE_NUMBER: ${{ github.event.issue.number }}
